export default [
  {
    icon: "",
    url: "https://baidu.com",
    name: "百度一下",
    description: "百度搜索",
    category: "Search Engine",
  },
  {
    icon: "",
    url: "https://google.com.hk",
    name: "谷歌搜索",
    description: "谷歌搜索",
    category: "Search Engine",
  },
  {
    icon: "",
    url: "https://github.com",
    name: "Github",
    description: "Github",
    category: "Programming",
  },
  {
    icon: "",
    url: "https://gitee.com",
    name: "码云",
    description: "码云",
    category: "Programming",
  },
  {
    icon: "",
    url: "https://gitlab.com",
    name: "GitLab",
    description: "GitLab",
    category: "Programming",
  },
  {
    icon: "",
    url: "https://coding.net",
    name: "Coding",
    description: "Coding",
    category: "Programming",
  },
  {
    icon: "",
    url: "https://bilibili.com",
    name: "Bilibili",
    description: "bilibili",
    category: "Video",
  },
  {
    icon: "",
    url: "https://v.qq.com",
    name: "腾讯视频",
    description: "腾讯视频",
    category: "Video",
  },
  {
    icon: "",
    url: "https://iqiyi.com",
    name: "爱奇艺",
    description: "爱奇艺",
    category: "Video",
  },
  {
    icon: "",
    url: "https://youku.com",
    name: "优酷视频",
    description: "优酷视频",
    category: "Video",
  },
  {
    icon: "",
    url: "https://youtube.com",
    name: "Youtube",
    description: "Youtube",
    category: "Video",
  },
  {
    icon: "",
    url: "https://twitter.com",
    name: "Twitter",
    description: "Twitter",
    category: "Social",
  },
  {
    icon: "",
    url: "https://facebook.com",
    name: "Facebook",
    description: "Facebook",
    category: "Social",
  },
  {
    icon: "",
    url: "https://instagram.com",
    name: "Instagram",
    description: "Instagram",
    category: "Social",
  },
];
